### ISSUE TITLE
Throwing errors on PHP inside <script> tags

### ISSUE THREAD

**Issue by zinefer** [SublimeLinter/SublimeLinter-jshint#35]
```
<html>
  <body>
    <script>
      console.log(<?= json_encode('hi mom') ?>);
    </script>
  </body>
</html>
```

Maybe nothing can be done ... Maybe not ...

**Comment by alexandre1985** [comment]
Sometimes putting php in quotes is not appropriate. For example, when there is a loop on php. Here is a screenshot of one case:
![captura de ecra de 2016-08-17 17 32 20](https://cloud.githubusercontent.com/assets/5586308/17932195/c1a8d508-6a06-11e6-9a25-0712f43bcf06.png)
What should I do in order for the php code to not appear as error? I have SublimeLinter-jshint and SublimeLinter-php .

**Comment by origamifreak2** [comment]
I also have many pieces of javascript with embedded php statements where it isn't appropriate to have quotes around the php statement. It would be a great benefit for jshint to handle embedded php, or at least just ignore it.

**Comment by v1xiii** [comment]
Has anyone found a solution to this yet?

**Comment by viable-hartman** [comment]
The best solution I have found for this is surrounding your php code like this...

/* jshint ignore:start */
var jsVariable = <?php echo json_encode(...PHP...CODE...); ?>;
/* jshint ignore:end */

...but even this is not great because it causes the jsVariable to throw errors in jshint, so you also have to add them to jshint's predef array to ignore the errors, which is obviously not ideal.
