### ISSUE TITLE
SublimeLinter-jshint v1.2.1 hangs the editor

### ISSUE THREAD

**Issue by neocoder** [SublimeLinter/SublimeLinter-jshint#61]
This happens on a fresh installation of ST3 ( on both the latest stable(3065) and latest dev(3069) builds ) on OSX 10.8.5.
When I open the js file there's no error hints in the interface but the editor works. Then I click the "Lint This View" from the menu and the editor hangs. I checked the running processes and there're two jshints running.
I copied the command which is executed by the jshint plugin ran it with passing the file contents to the stdin and it worked fine. It seems that the plugin cannot properly communicate with the child jshint process.

I also tried to install the SublimeLinter-jslint and it worked fine.

**Comment by mokkabonna** [comment]
The question is I guess if sublimelinter-jshint is responsible for spawning the two child processes. As I suspect the problem is related to that. Try a complete reboot
ensure there are no jshint processes running, and then start ST3 and observe. I have no access to OSX so cannot debug, works fine for me on ubuntu with 3065 build.

**Comment by braver** [comment]
Shouldn’t be an issue with recent versions.
