### ISSUE TITLE
Not linting when syntax is Gulpfile JS

### ISSUE THREAD

**Issue by skube** [SublimeLinter/SublimeLinter-jshint#63]
Should this be working when set to `Gulpfile JS` syntax? :confused:

**Comment by KyleRoss** [comment]
The author has hardcoded the syntax names to check with JSHint. You need to find the proper name for the Gulpfile JS syntax plugin you are using (usually the name of the `.tmLanguage` file) and then:

`Preferences` > `Browse Packages` > `SublimeLinter-jshint` and edit `linter.py`. On line 21 ([as seen here](https://github.com/SublimeLinter/SublimeLinter-jshint/blob/master/linter.py#L21)), add the name of the syntax to the list. Save the file and clear the caches in Sublime Linter. Should work now.

Keep in mind, you will need to remove this plugin from Package Control if you are using it, otherwise if an update is ever pushed out, this change will be removed.

I may give it a shot and do a pull request to make this configurable, but I'm a bit rusty on Python.

**Comment by paradox41** [comment]
You could also update the `syntax_map` in `SublimeLinter.sublime-settings` (`Preferences` > `Package Settings` > `SublimeLinter` > `Settings - User`) to be something like this:

```json
"syntax_map": {
    "Gulpfile JS": "javascript",
    "html (django)": "html",
    "html (rails)": "html",
    "html 5": "html",
    "javascript (babel)": "javascript",
    "php": "html",
    "python django": "python"
},
```
