### ISSUE TITLE
Lint only when .jshintrc is present

### ISSUE THREAD

**Issue by veob** [SublimeLinter/SublimeLinter-jshint#80]
In some project I have .eslintrc file only, but jshint is still trying to lint my code.  How can I disable jshint, when there is no .jshintrc file in root folder?

**Comment by tomwayson** [comment]
I agree, this would be a valuable feature.

**Comment by mokkabonna** [comment]
This linter lints all files that match the javascript syntax, and have default options (through jshint). It is out of scope of this linter to disable itself when other linters are present.

Either manually disable it or maybe there exists a package that can disable/enable packages given certain criteria. So that changing projects disables/enables a set of packages.

**Comment by clempat** [comment]
Sad this did not go through. I will have to find an alternative to continue using sublime over atom. As I don't want to make any extra file on project using eslint for example... At least on atom the jshint plugin integrates it.
